spring:
  profiles:
    active: local
  application:
    name: CodeAI
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_ai
    username: root
    password: root
server:
  servlet:
    context-path: /api
  port: 8082
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.xyy.codeai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

